// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public interface AccessPermissionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.surveillance_security.AccessPermissionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string credentials = 1;</code>
   */
  java.lang.String getCredentials();
  /**
   * <code>string credentials = 1;</code>
   */
  com.google.protobuf.ByteString
      getCredentialsBytes();

  /**
   * <code>string area_id = 2;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();
}
