// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public interface AccessPermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.surveillance_security.AccessPermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.building.surveillance_security.AccessPermissionResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.building.surveillance_security.AccessPermissionResponse.Status status = 1;</code>
   */
  building.surveillance_security.AccessPermissionResponse.Status getStatus();

  /**
   * <code>string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
