// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

/**
 * Protobuf type {@code building.surveillance_security.AlertIntrusionResponse}
 */
public  final class AlertIntrusionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:building.surveillance_security.AlertIntrusionResponse)
    AlertIntrusionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertIntrusionResponse.newBuilder() to construct.
  private AlertIntrusionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertIntrusionResponse() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AlertIntrusionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            building.surveillance_security.DateTime.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(building.surveillance_security.DateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            building.surveillance_security.AlertIntrusionResponse.class, building.surveillance_security.AlertIntrusionResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code building.surveillance_security.AlertIntrusionResponse.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACKNOWLEDGED = 0;</code>
     */
    ACKNOWLEDGED(0),
    /**
     * <code>UNACKNOWLEDGED = 1;</code>
     */
    UNACKNOWLEDGED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACKNOWLEDGED = 0;</code>
     */
    public static final int ACKNOWLEDGED_VALUE = 0;
    /**
     * <code>UNACKNOWLEDGED = 1;</code>
     */
    public static final int UNACKNOWLEDGED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return ACKNOWLEDGED;
        case 1: return UNACKNOWLEDGED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return building.surveillance_security.AlertIntrusionResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:building.surveillance_security.AlertIntrusionResponse.Status)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
   */
  public building.surveillance_security.AlertIntrusionResponse.Status getStatus() {
    @SuppressWarnings("deprecation")
    building.surveillance_security.AlertIntrusionResponse.Status result = building.surveillance_security.AlertIntrusionResponse.Status.valueOf(status_);
    return result == null ? building.surveillance_security.AlertIntrusionResponse.Status.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private building.surveillance_security.DateTime timestamp_;
  /**
   * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
   */
  public building.surveillance_security.DateTime getTimestamp() {
    return timestamp_ == null ? building.surveillance_security.DateTime.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
   */
  public building.surveillance_security.DateTimeOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != building.surveillance_security.AlertIntrusionResponse.Status.ACKNOWLEDGED.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != building.surveillance_security.AlertIntrusionResponse.Status.ACKNOWLEDGED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof building.surveillance_security.AlertIntrusionResponse)) {
      return super.equals(obj);
    }
    building.surveillance_security.AlertIntrusionResponse other = (building.surveillance_security.AlertIntrusionResponse) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(building.surveillance_security.AlertIntrusionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code building.surveillance_security.AlertIntrusionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:building.surveillance_security.AlertIntrusionResponse)
      building.surveillance_security.AlertIntrusionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              building.surveillance_security.AlertIntrusionResponse.class, building.surveillance_security.AlertIntrusionResponse.Builder.class);
    }

    // Construct using building.surveillance_security.AlertIntrusionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor;
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionResponse getDefaultInstanceForType() {
      return building.surveillance_security.AlertIntrusionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionResponse build() {
      building.surveillance_security.AlertIntrusionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionResponse buildPartial() {
      building.surveillance_security.AlertIntrusionResponse result = new building.surveillance_security.AlertIntrusionResponse(this);
      result.status_ = status_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof building.surveillance_security.AlertIntrusionResponse) {
        return mergeFrom((building.surveillance_security.AlertIntrusionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(building.surveillance_security.AlertIntrusionResponse other) {
      if (other == building.surveillance_security.AlertIntrusionResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      building.surveillance_security.AlertIntrusionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (building.surveillance_security.AlertIntrusionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
     */
    public building.surveillance_security.AlertIntrusionResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      building.surveillance_security.AlertIntrusionResponse.Status result = building.surveillance_security.AlertIntrusionResponse.Status.valueOf(status_);
      return result == null ? building.surveillance_security.AlertIntrusionResponse.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
     */
    public Builder setStatus(building.surveillance_security.AlertIntrusionResponse.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.building.surveillance_security.AlertIntrusionResponse.Status status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private building.surveillance_security.DateTime timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        building.surveillance_security.DateTime, building.surveillance_security.DateTime.Builder, building.surveillance_security.DateTimeOrBuilder> timestampBuilder_;
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public building.surveillance_security.DateTime getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? building.surveillance_security.DateTime.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public Builder setTimestamp(building.surveillance_security.DateTime value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public Builder setTimestamp(
        building.surveillance_security.DateTime.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public Builder mergeTimestamp(building.surveillance_security.DateTime value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            building.surveillance_security.DateTime.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public building.surveillance_security.DateTime.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    public building.surveillance_security.DateTimeOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            building.surveillance_security.DateTime.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.building.surveillance_security.DateTime timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        building.surveillance_security.DateTime, building.surveillance_security.DateTime.Builder, building.surveillance_security.DateTimeOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            building.surveillance_security.DateTime, building.surveillance_security.DateTime.Builder, building.surveillance_security.DateTimeOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:building.surveillance_security.AlertIntrusionResponse)
  }

  // @@protoc_insertion_point(class_scope:building.surveillance_security.AlertIntrusionResponse)
  private static final building.surveillance_security.AlertIntrusionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new building.surveillance_security.AlertIntrusionResponse();
  }

  public static building.surveillance_security.AlertIntrusionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertIntrusionResponse>
      PARSER = new com.google.protobuf.AbstractParser<AlertIntrusionResponse>() {
    @java.lang.Override
    public AlertIntrusionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AlertIntrusionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AlertIntrusionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertIntrusionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public building.surveillance_security.AlertIntrusionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

