// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public interface AlertIntrusionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.surveillance_security.AlertIntrusionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();

  /**
   * <code>string alert_code = 2;</code>
   */
  java.lang.String getAlertCode();
  /**
   * <code>string alert_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getAlertCodeBytes();
}
