// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

/**
 * <pre>
 * Request and response messages
 * </pre>
 *
 * Protobuf type {@code building.surveillance_security.AlertIntrusionRequest}
 */
public  final class AlertIntrusionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:building.surveillance_security.AlertIntrusionRequest)
    AlertIntrusionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertIntrusionRequest.newBuilder() to construct.
  private AlertIntrusionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertIntrusionRequest() {
    areaId_ = "";
    alertCode_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AlertIntrusionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            areaId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            alertCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            building.surveillance_security.AlertIntrusionRequest.class, building.surveillance_security.AlertIntrusionRequest.Builder.class);
  }

  public static final int AREA_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object areaId_;
  /**
   * <code>string area_id = 1;</code>
   */
  public java.lang.String getAreaId() {
    java.lang.Object ref = areaId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaId_ = s;
      return s;
    }
  }
  /**
   * <code>string area_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaIdBytes() {
    java.lang.Object ref = areaId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERT_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object alertCode_;
  /**
   * <code>string alert_code = 2;</code>
   */
  public java.lang.String getAlertCode() {
    java.lang.Object ref = alertCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertCode_ = s;
      return s;
    }
  }
  /**
   * <code>string alert_code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAlertCodeBytes() {
    java.lang.Object ref = alertCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, areaId_);
    }
    if (!getAlertCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, alertCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, areaId_);
    }
    if (!getAlertCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, alertCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof building.surveillance_security.AlertIntrusionRequest)) {
      return super.equals(obj);
    }
    building.surveillance_security.AlertIntrusionRequest other = (building.surveillance_security.AlertIntrusionRequest) obj;

    boolean result = true;
    result = result && getAreaId()
        .equals(other.getAreaId());
    result = result && getAlertCode()
        .equals(other.getAlertCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAreaId().hashCode();
    hash = (37 * hash) + ALERT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.AlertIntrusionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(building.surveillance_security.AlertIntrusionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request and response messages
   * </pre>
   *
   * Protobuf type {@code building.surveillance_security.AlertIntrusionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:building.surveillance_security.AlertIntrusionRequest)
      building.surveillance_security.AlertIntrusionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              building.surveillance_security.AlertIntrusionRequest.class, building.surveillance_security.AlertIntrusionRequest.Builder.class);
    }

    // Construct using building.surveillance_security.AlertIntrusionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      areaId_ = "";

      alertCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor;
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionRequest getDefaultInstanceForType() {
      return building.surveillance_security.AlertIntrusionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionRequest build() {
      building.surveillance_security.AlertIntrusionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public building.surveillance_security.AlertIntrusionRequest buildPartial() {
      building.surveillance_security.AlertIntrusionRequest result = new building.surveillance_security.AlertIntrusionRequest(this);
      result.areaId_ = areaId_;
      result.alertCode_ = alertCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof building.surveillance_security.AlertIntrusionRequest) {
        return mergeFrom((building.surveillance_security.AlertIntrusionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(building.surveillance_security.AlertIntrusionRequest other) {
      if (other == building.surveillance_security.AlertIntrusionRequest.getDefaultInstance()) return this;
      if (!other.getAreaId().isEmpty()) {
        areaId_ = other.areaId_;
        onChanged();
      }
      if (!other.getAlertCode().isEmpty()) {
        alertCode_ = other.alertCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      building.surveillance_security.AlertIntrusionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (building.surveillance_security.AlertIntrusionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object areaId_ = "";
    /**
     * <code>string area_id = 1;</code>
     */
    public java.lang.String getAreaId() {
      java.lang.Object ref = areaId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaIdBytes() {
      java.lang.Object ref = areaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder setAreaId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder clearAreaId() {
      
      areaId_ = getDefaultInstance().getAreaId();
      onChanged();
      return this;
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder setAreaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object alertCode_ = "";
    /**
     * <code>string alert_code = 2;</code>
     */
    public java.lang.String getAlertCode() {
      java.lang.Object ref = alertCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alert_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlertCodeBytes() {
      java.lang.Object ref = alertCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alert_code = 2;</code>
     */
    public Builder setAlertCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alertCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alert_code = 2;</code>
     */
    public Builder clearAlertCode() {
      
      alertCode_ = getDefaultInstance().getAlertCode();
      onChanged();
      return this;
    }
    /**
     * <code>string alert_code = 2;</code>
     */
    public Builder setAlertCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alertCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:building.surveillance_security.AlertIntrusionRequest)
  }

  // @@protoc_insertion_point(class_scope:building.surveillance_security.AlertIntrusionRequest)
  private static final building.surveillance_security.AlertIntrusionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new building.surveillance_security.AlertIntrusionRequest();
  }

  public static building.surveillance_security.AlertIntrusionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertIntrusionRequest>
      PARSER = new com.google.protobuf.AbstractParser<AlertIntrusionRequest>() {
    @java.lang.Override
    public AlertIntrusionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AlertIntrusionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AlertIntrusionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertIntrusionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public building.surveillance_security.AlertIntrusionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

