// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public final class BuildingSurveillanceSecurityService {
  private BuildingSurveillanceSecurityService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_AlertIntrusionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_AlertIntrusionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_DateTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_DateTime_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_AccessPermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_AccessPermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_AccessPermissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_AccessPermissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_StreamingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_StreamingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_surveillance_security_StreamingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_surveillance_security_StreamingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)BuildingSurveillanceSecurityService.pr" +
      "oto\022\036building.surveillance_security\"<\n\025A" +
      "lertIntrusionRequest\022\017\n\007area_id\030\001 \001(\t\022\022\n" +
      "\nalert_code\030\002 \001(\t\"\324\001\n\026AlertIntrusionResp" +
      "onse\022M\n\006status\030\001 \001(\0162=.building.surveill" +
      "ance_security.AlertIntrusionResponse.Sta" +
      "tus\022;\n\ttimestamp\030\002 \001(\0132(.building.survei" +
      "llance_security.DateTime\".\n\006Status\022\020\n\014AC" +
      "KNOWLEDGED\020\000\022\022\n\016UNACKNOWLEDGED\020\001\"b\n\010Date" +
      "Time\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day" +
      "\030\003 \001(\005\022\014\n\004hour\030\004 \001(\005\022\016\n\006minute\030\005 \001(\005\022\016\n\006" +
      "second\030\006 \001(\005\"?\n\027AccessPermissionRequest\022" +
      "\023\n\013credentials\030\001 \001(\t\022\017\n\007area_id\030\002 \001(\t\"\263\001" +
      "\n\030AccessPermissionResponse\022O\n\006status\030\001 \001" +
      "(\0162?.building.surveillance_security.Acce" +
      "ssPermissionResponse.Status\022\025\n\rerror_mes" +
      "sage\030\002 \001(\t\"/\n\006Status\022\022\n\016ACCESS_GRANTED\020\000" +
      "\022\021\n\rACCESS_DENIED\020\001\"\250\001\n\020StreamingRequest" +
      "\022\017\n\007area_id\030\001 \001(\t\022O\n\007command\030\002 \001(\0162>.bui" +
      "lding.surveillance_security.StreamingReq" +
      "uest.StreamCommand\"2\n\rStreamCommand\022\020\n\014S" +
      "TART_STREAM\020\000\022\017\n\013STOP_STREAM\020\001\">\n\021Stream" +
      "ingResponse\022\022\n\nvideo_data\030\001 \001(\014\022\025\n\rerror" +
      "_message\030\002 \001(\t2\271\004\n\033SurveillanceSecurityS" +
      "ervice\022\201\001\n\016alertIntrusion\0225.building.sur" +
      "veillance_security.AlertIntrusionRequest" +
      "\0326.building.surveillance_security.AlertI" +
      "ntrusionResponse\"\000\022\210\001\n\023continuousAlertFe" +
      "ed\0225.building.surveillance_security.Aler" +
      "tIntrusionRequest\0326.building.surveillanc" +
      "e_security.AlertIntrusionResponse\"\0000\001\022\216\001" +
      "\n\025batchAccessPermission\0227.building.surve" +
      "illance_security.AccessPermissionRequest" +
      "\0328.building.surveillance_security.Access" +
      "PermissionResponse\"\000(\001\022z\n\rstreamingFeed\022" +
      "0.building.surveillance_security.Streami" +
      "ngRequest\0321.building.surveillance_securi" +
      "ty.StreamingResponse\"\000(\0010\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_surveillance_security_AlertIntrusionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_AlertIntrusionRequest_descriptor,
        new java.lang.String[] { "AreaId", "AlertCode", });
    internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_building_surveillance_security_AlertIntrusionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_AlertIntrusionResponse_descriptor,
        new java.lang.String[] { "Status", "Timestamp", });
    internal_static_building_surveillance_security_DateTime_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_building_surveillance_security_DateTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_DateTime_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Hour", "Minute", "Second", });
    internal_static_building_surveillance_security_AccessPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_building_surveillance_security_AccessPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_AccessPermissionRequest_descriptor,
        new java.lang.String[] { "Credentials", "AreaId", });
    internal_static_building_surveillance_security_AccessPermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_building_surveillance_security_AccessPermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_AccessPermissionResponse_descriptor,
        new java.lang.String[] { "Status", "ErrorMessage", });
    internal_static_building_surveillance_security_StreamingRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_building_surveillance_security_StreamingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_StreamingRequest_descriptor,
        new java.lang.String[] { "AreaId", "Command", });
    internal_static_building_surveillance_security_StreamingResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_building_surveillance_security_StreamingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_surveillance_security_StreamingResponse_descriptor,
        new java.lang.String[] { "VideoData", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
