// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

/**
 * Protobuf type {@code building.surveillance_security.StreamingRequest}
 */
public  final class StreamingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:building.surveillance_security.StreamingRequest)
    StreamingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingRequest.newBuilder() to construct.
  private StreamingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingRequest() {
    areaId_ = "";
    command_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            areaId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_StreamingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_StreamingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            building.surveillance_security.StreamingRequest.class, building.surveillance_security.StreamingRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code building.surveillance_security.StreamingRequest.StreamCommand}
   */
  public enum StreamCommand
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START_STREAM = 0;</code>
     */
    START_STREAM(0),
    /**
     * <code>STOP_STREAM = 1;</code>
     */
    STOP_STREAM(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>START_STREAM = 0;</code>
     */
    public static final int START_STREAM_VALUE = 0;
    /**
     * <code>STOP_STREAM = 1;</code>
     */
    public static final int STOP_STREAM_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StreamCommand valueOf(int value) {
      return forNumber(value);
    }

    public static StreamCommand forNumber(int value) {
      switch (value) {
        case 0: return START_STREAM;
        case 1: return STOP_STREAM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StreamCommand>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StreamCommand> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StreamCommand>() {
            public StreamCommand findValueByNumber(int number) {
              return StreamCommand.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return building.surveillance_security.StreamingRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final StreamCommand[] VALUES = values();

    public static StreamCommand valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StreamCommand(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:building.surveillance_security.StreamingRequest.StreamCommand)
  }

  public static final int AREA_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object areaId_;
  /**
   * <code>string area_id = 1;</code>
   */
  public java.lang.String getAreaId() {
    java.lang.Object ref = areaId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaId_ = s;
      return s;
    }
  }
  /**
   * <code>string area_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaIdBytes() {
    java.lang.Object ref = areaId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 2;
  private int command_;
  /**
   * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
   */
  public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
   */
  public building.surveillance_security.StreamingRequest.StreamCommand getCommand() {
    @SuppressWarnings("deprecation")
    building.surveillance_security.StreamingRequest.StreamCommand result = building.surveillance_security.StreamingRequest.StreamCommand.valueOf(command_);
    return result == null ? building.surveillance_security.StreamingRequest.StreamCommand.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, areaId_);
    }
    if (command_ != building.surveillance_security.StreamingRequest.StreamCommand.START_STREAM.getNumber()) {
      output.writeEnum(2, command_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, areaId_);
    }
    if (command_ != building.surveillance_security.StreamingRequest.StreamCommand.START_STREAM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, command_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof building.surveillance_security.StreamingRequest)) {
      return super.equals(obj);
    }
    building.surveillance_security.StreamingRequest other = (building.surveillance_security.StreamingRequest) obj;

    boolean result = true;
    result = result && getAreaId()
        .equals(other.getAreaId());
    result = result && command_ == other.command_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAreaId().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static building.surveillance_security.StreamingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.StreamingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static building.surveillance_security.StreamingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.surveillance_security.StreamingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(building.surveillance_security.StreamingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code building.surveillance_security.StreamingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:building.surveillance_security.StreamingRequest)
      building.surveillance_security.StreamingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_StreamingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_StreamingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              building.surveillance_security.StreamingRequest.class, building.surveillance_security.StreamingRequest.Builder.class);
    }

    // Construct using building.surveillance_security.StreamingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      areaId_ = "";

      command_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return building.surveillance_security.BuildingSurveillanceSecurityService.internal_static_building_surveillance_security_StreamingRequest_descriptor;
    }

    @java.lang.Override
    public building.surveillance_security.StreamingRequest getDefaultInstanceForType() {
      return building.surveillance_security.StreamingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public building.surveillance_security.StreamingRequest build() {
      building.surveillance_security.StreamingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public building.surveillance_security.StreamingRequest buildPartial() {
      building.surveillance_security.StreamingRequest result = new building.surveillance_security.StreamingRequest(this);
      result.areaId_ = areaId_;
      result.command_ = command_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof building.surveillance_security.StreamingRequest) {
        return mergeFrom((building.surveillance_security.StreamingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(building.surveillance_security.StreamingRequest other) {
      if (other == building.surveillance_security.StreamingRequest.getDefaultInstance()) return this;
      if (!other.getAreaId().isEmpty()) {
        areaId_ = other.areaId_;
        onChanged();
      }
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      building.surveillance_security.StreamingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (building.surveillance_security.StreamingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object areaId_ = "";
    /**
     * <code>string area_id = 1;</code>
     */
    public java.lang.String getAreaId() {
      java.lang.Object ref = areaId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaIdBytes() {
      java.lang.Object ref = areaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder setAreaId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder clearAreaId() {
      
      areaId_ = getDefaultInstance().getAreaId();
      onChanged();
      return this;
    }
    /**
     * <code>string area_id = 1;</code>
     */
    public Builder setAreaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaId_ = value;
      onChanged();
      return this;
    }

    private int command_ = 0;
    /**
     * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
     */
    public Builder setCommandValue(int value) {
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
     */
    public building.surveillance_security.StreamingRequest.StreamCommand getCommand() {
      @SuppressWarnings("deprecation")
      building.surveillance_security.StreamingRequest.StreamCommand result = building.surveillance_security.StreamingRequest.StreamCommand.valueOf(command_);
      return result == null ? building.surveillance_security.StreamingRequest.StreamCommand.UNRECOGNIZED : result;
    }
    /**
     * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
     */
    public Builder setCommand(building.surveillance_security.StreamingRequest.StreamCommand value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:building.surveillance_security.StreamingRequest)
  }

  // @@protoc_insertion_point(class_scope:building.surveillance_security.StreamingRequest)
  private static final building.surveillance_security.StreamingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new building.surveillance_security.StreamingRequest();
  }

  public static building.surveillance_security.StreamingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamingRequest>() {
    @java.lang.Override
    public StreamingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public building.surveillance_security.StreamingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

