// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public interface StreamingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.surveillance_security.StreamingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();

  /**
   * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
   */
  int getCommandValue();
  /**
   * <code>.building.surveillance_security.StreamingRequest.StreamCommand command = 2;</code>
   */
  building.surveillance_security.StreamingRequest.StreamCommand getCommand();
}
