// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingSurveillanceSecurityService.proto

package building.surveillance_security;

public interface StreamingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.surveillance_security.StreamingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes video_data = 1;</code>
   */
  com.google.protobuf.ByteString getVideoData();

  /**
   * <code>string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
