// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building;

public final class ClimateControlService {
  private ClimateControlService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_AdjustTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_AdjustTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_AdjustTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_AdjustTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_CurrentTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_CurrentTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_CurrentTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_CurrentTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_HVACConditionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_HVACConditionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_HVACConditionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_HVACConditionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ClimateControlService.proto\022\010building\"" +
      "@\n\030AdjustTemperatureRequest\022\017\n\007area_id\030\001" +
      " \001(\t\022\023\n\013temperature\030\002 \001(\002\"C\n\031AdjustTempe" +
      "ratureResponse\022\017\n\007success\030\001 \001(\010\022\025\n\rerror" +
      "_message\030\002 \001(\t\",\n\031CurrentTemperatureRequ" +
      "est\022\017\n\007area_id\030\001 \001(\t\"^\n\032CurrentTemperatu" +
      "reResponse\022\023\n\013temperature\030\001 \001(\002\022\020\n\010humid" +
      "ity\030\002 \001(\002\022\031\n\021air_quality_index\030\003 \001(\005\"\'\n\024" +
      "HVACConditionRequest\022\017\n\007area_id\030\001 \001(\t\"q\n" +
      "\025HVACConditionResponse\022\016\n\006status\030\001 \001(\010\022\033" +
      "\n\023current_temperature\030\002 \001(\002\022\027\n\017set_tempe" +
      "rature\030\003 \001(\002\022\022\n\nerror_code\030\004 \001(\t2\253\002\n\017Bui" +
      "ldingService\022^\n\021adjustTemperature\022\".buil" +
      "ding.AdjustTemperatureRequest\032#.building" +
      ".AdjustTemperatureResponse\"\000\022a\n\022currentT" +
      "emperature\022#.building.CurrentTemperature" +
      "Request\032$.building.CurrentTemperatureRes" +
      "ponse\"\000\022U\n\020getHVACCondition\022\036.building.H" +
      "VACConditionRequest\032\037.building.HVACCondi" +
      "tionResponse\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_building_AdjustTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_AdjustTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_AdjustTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", "Temperature", });
    internal_static_building_AdjustTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_building_AdjustTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_AdjustTemperatureResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", });
    internal_static_building_CurrentTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_building_CurrentTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_CurrentTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_building_CurrentTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_building_CurrentTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_CurrentTemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "AirQualityIndex", });
    internal_static_building_HVACConditionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_building_HVACConditionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_HVACConditionRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_building_HVACConditionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_building_HVACConditionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_HVACConditionResponse_descriptor,
        new java.lang.String[] { "Status", "CurrentTemperature", "SetTemperature", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
