// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building;

public interface CurrentTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.CurrentTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();
}
