// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building;

public interface HVACConditionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.HVACConditionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>float current_temperature = 2;</code>
   */
  float getCurrentTemperature();

  /**
   * <code>float set_temperature = 3;</code>
   */
  float getSetTemperature();

  /**
   * <code>string error_code = 4;</code>
   */
  java.lang.String getErrorCode();
  /**
   * <code>string error_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();
}
