// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building.climate_control;

public interface AdjustTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.climate_control.AdjustTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *identifier for the room
   * </pre>
   *
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <pre>
   *identifier for the room
   * </pre>
   *
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();

  /**
   * <pre>
   *desired temperature
   * </pre>
   *
   * <code>float temperature = 2;</code>
   */
  float getTemperature();
}
