// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building.climate_control;

public interface AdjustTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.climate_control.AdjustTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
