// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building.climate_control;

public final class ClimateControlService {
  private ClimateControlService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_AdjustTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_AdjustTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_AdjustTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_AdjustTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_CurrentTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_CurrentTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_CurrentTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_CurrentTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_HVACConditionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_HVACConditionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_climate_control_HVACConditionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_climate_control_HVACConditionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ClimateControlService.proto\022\030building." +
      "climate_control\"@\n\030AdjustTemperatureRequ" +
      "est\022\017\n\007area_id\030\001 \001(\t\022\023\n\013temperature\030\002 \001(" +
      "\002\"C\n\031AdjustTemperatureResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\022\025\n\rerror_message\030\002 \001(\t\",\n\031Curren" +
      "tTemperatureRequest\022\017\n\007area_id\030\001 \001(\t\"^\n\032" +
      "CurrentTemperatureResponse\022\023\n\013temperatur" +
      "e\030\001 \001(\002\022\020\n\010humidity\030\002 \001(\002\022\031\n\021air_quality" +
      "_index\030\003 \001(\005\"\'\n\024HVACConditionRequest\022\017\n\007" +
      "area_id\030\001 \001(\t\"q\n\025HVACConditionResponse\022\016" +
      "\n\006status\030\001 \001(\010\022\033\n\023current_temperature\030\002 " +
      "\001(\002\022\027\n\017set_temperature\030\003 \001(\002\022\022\n\nerror_co" +
      "de\030\004 \001(\t2\214\003\n\017BuildingService\022~\n\021adjustTe" +
      "mperature\0222.building.climate_control.Adj" +
      "ustTemperatureRequest\0323.building.climate" +
      "_control.AdjustTemperatureResponse\"\000\022\201\001\n" +
      "\022currentTemperature\0223.building.climate_c" +
      "ontrol.CurrentTemperatureRequest\0324.build" +
      "ing.climate_control.CurrentTemperatureRe" +
      "sponse\"\000\022u\n\020getHVACCondition\022..building." +
      "climate_control.HVACConditionRequest\032/.b" +
      "uilding.climate_control.HVACConditionRes" +
      "ponse\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_building_climate_control_AdjustTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_climate_control_AdjustTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_AdjustTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", "Temperature", });
    internal_static_building_climate_control_AdjustTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_building_climate_control_AdjustTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_AdjustTemperatureResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", });
    internal_static_building_climate_control_CurrentTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_building_climate_control_CurrentTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_CurrentTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_building_climate_control_CurrentTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_building_climate_control_CurrentTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_CurrentTemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "AirQualityIndex", });
    internal_static_building_climate_control_HVACConditionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_building_climate_control_HVACConditionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_HVACConditionRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_building_climate_control_HVACConditionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_building_climate_control_HVACConditionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_climate_control_HVACConditionResponse_descriptor,
        new java.lang.String[] { "Status", "CurrentTemperature", "SetTemperature", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
