// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building.climate_control;

public interface CurrentTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.climate_control.CurrentTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   */
  float getTemperature();

  /**
   * <code>float humidity = 2;</code>
   */
  float getHumidity();

  /**
   * <code>int32 air_quality_index = 3;</code>
   */
  int getAirQualityIndex();
}
