// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateControlService.proto

package building.climate_control;

/**
 * <pre>
 *response for current temperature, humidity and air quality index
 * </pre>
 *
 * Protobuf type {@code building.climate_control.CurrentTemperatureResponse}
 */
public  final class CurrentTemperatureResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:building.climate_control.CurrentTemperatureResponse)
    CurrentTemperatureResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CurrentTemperatureResponse.newBuilder() to construct.
  private CurrentTemperatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CurrentTemperatureResponse() {
    temperature_ = 0F;
    humidity_ = 0F;
    airQualityIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CurrentTemperatureResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            temperature_ = input.readFloat();
            break;
          }
          case 21: {

            humidity_ = input.readFloat();
            break;
          }
          case 24: {

            airQualityIndex_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return building.climate_control.ClimateControlService.internal_static_building_climate_control_CurrentTemperatureResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return building.climate_control.ClimateControlService.internal_static_building_climate_control_CurrentTemperatureResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            building.climate_control.CurrentTemperatureResponse.class, building.climate_control.CurrentTemperatureResponse.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private float temperature_;
  /**
   * <code>float temperature = 1;</code>
   */
  public float getTemperature() {
    return temperature_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 2;
  private float humidity_;
  /**
   * <code>float humidity = 2;</code>
   */
  public float getHumidity() {
    return humidity_;
  }

  public static final int AIR_QUALITY_INDEX_FIELD_NUMBER = 3;
  private int airQualityIndex_;
  /**
   * <code>int32 air_quality_index = 3;</code>
   */
  public int getAirQualityIndex() {
    return airQualityIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperature_ != 0F) {
      output.writeFloat(1, temperature_);
    }
    if (humidity_ != 0F) {
      output.writeFloat(2, humidity_);
    }
    if (airQualityIndex_ != 0) {
      output.writeInt32(3, airQualityIndex_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperature_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, temperature_);
    }
    if (humidity_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, humidity_);
    }
    if (airQualityIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, airQualityIndex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof building.climate_control.CurrentTemperatureResponse)) {
      return super.equals(obj);
    }
    building.climate_control.CurrentTemperatureResponse other = (building.climate_control.CurrentTemperatureResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getTemperature())
        == java.lang.Float.floatToIntBits(
            other.getTemperature()));
    result = result && (
        java.lang.Float.floatToIntBits(getHumidity())
        == java.lang.Float.floatToIntBits(
            other.getHumidity()));
    result = result && (getAirQualityIndex()
        == other.getAirQualityIndex());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHumidity());
    hash = (37 * hash) + AIR_QUALITY_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAirQualityIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.climate_control.CurrentTemperatureResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static building.climate_control.CurrentTemperatureResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static building.climate_control.CurrentTemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(building.climate_control.CurrentTemperatureResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *response for current temperature, humidity and air quality index
   * </pre>
   *
   * Protobuf type {@code building.climate_control.CurrentTemperatureResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:building.climate_control.CurrentTemperatureResponse)
      building.climate_control.CurrentTemperatureResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return building.climate_control.ClimateControlService.internal_static_building_climate_control_CurrentTemperatureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return building.climate_control.ClimateControlService.internal_static_building_climate_control_CurrentTemperatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              building.climate_control.CurrentTemperatureResponse.class, building.climate_control.CurrentTemperatureResponse.Builder.class);
    }

    // Construct using building.climate_control.CurrentTemperatureResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperature_ = 0F;

      humidity_ = 0F;

      airQualityIndex_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return building.climate_control.ClimateControlService.internal_static_building_climate_control_CurrentTemperatureResponse_descriptor;
    }

    @java.lang.Override
    public building.climate_control.CurrentTemperatureResponse getDefaultInstanceForType() {
      return building.climate_control.CurrentTemperatureResponse.getDefaultInstance();
    }

    @java.lang.Override
    public building.climate_control.CurrentTemperatureResponse build() {
      building.climate_control.CurrentTemperatureResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public building.climate_control.CurrentTemperatureResponse buildPartial() {
      building.climate_control.CurrentTemperatureResponse result = new building.climate_control.CurrentTemperatureResponse(this);
      result.temperature_ = temperature_;
      result.humidity_ = humidity_;
      result.airQualityIndex_ = airQualityIndex_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof building.climate_control.CurrentTemperatureResponse) {
        return mergeFrom((building.climate_control.CurrentTemperatureResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(building.climate_control.CurrentTemperatureResponse other) {
      if (other == building.climate_control.CurrentTemperatureResponse.getDefaultInstance()) return this;
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getHumidity() != 0F) {
        setHumidity(other.getHumidity());
      }
      if (other.getAirQualityIndex() != 0) {
        setAirQualityIndex(other.getAirQualityIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      building.climate_control.CurrentTemperatureResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (building.climate_control.CurrentTemperatureResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 1;</code>
     */
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 1;</code>
     */
    public Builder setTemperature(float value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 1;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float humidity_ ;
    /**
     * <code>float humidity = 2;</code>
     */
    public float getHumidity() {
      return humidity_;
    }
    /**
     * <code>float humidity = 2;</code>
     */
    public Builder setHumidity(float value) {
      
      humidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float humidity = 2;</code>
     */
    public Builder clearHumidity() {
      
      humidity_ = 0F;
      onChanged();
      return this;
    }

    private int airQualityIndex_ ;
    /**
     * <code>int32 air_quality_index = 3;</code>
     */
    public int getAirQualityIndex() {
      return airQualityIndex_;
    }
    /**
     * <code>int32 air_quality_index = 3;</code>
     */
    public Builder setAirQualityIndex(int value) {
      
      airQualityIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 air_quality_index = 3;</code>
     */
    public Builder clearAirQualityIndex() {
      
      airQualityIndex_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:building.climate_control.CurrentTemperatureResponse)
  }

  // @@protoc_insertion_point(class_scope:building.climate_control.CurrentTemperatureResponse)
  private static final building.climate_control.CurrentTemperatureResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new building.climate_control.CurrentTemperatureResponse();
  }

  public static building.climate_control.CurrentTemperatureResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CurrentTemperatureResponse>
      PARSER = new com.google.protobuf.AbstractParser<CurrentTemperatureResponse>() {
    @java.lang.Override
    public CurrentTemperatureResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CurrentTemperatureResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CurrentTemperatureResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CurrentTemperatureResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public building.climate_control.CurrentTemperatureResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

