// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IlluminationManagementService.proto

package building.illumination_control;

public final class IlluminationManagementServiceOuterClass {
  private IlluminationManagementServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_ModifyLightIntensityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_ModifyLightIntensityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_ModifyLightIntensityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_ModifyLightIntensityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_LightStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_LightStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_LightStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_LightStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_ChangeLightStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_ChangeLightStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_illumination_control_ChangeLightStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_illumination_control_ChangeLightStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#IlluminationManagementService.proto\022\035b" +
      "uilding.illumination_control\"A\n\033ModifyLi" +
      "ghtIntensityRequest\022\017\n\007area_id\030\001 \001(\t\022\021\n\t" +
      "intensity\030\002 \001(\005\"F\n\034ModifyLightIntensityR" +
      "esponse\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_messag" +
      "e\030\002 \001(\t\"%\n\022LightStatusRequest\022\017\n\007area_id" +
      "\030\001 \001(\t\"@\n\023LightStatusResponse\022\016\n\006status\030" +
      "\001 \001(\010\022\031\n\021current_intensity\030\002 \001(\005\";\n\030Chan" +
      "geLightStatusRequest\022\017\n\007area_id\030\001 \001(\t\022\016\n" +
      "\006status\030\002 \001(\010\"C\n\031ChangeLightStatusRespon" +
      "se\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message\030\002 \001" +
      "(\t2\266\003\n\035IlluminationManagementService\022\221\001\n" +
      "\024modifyLightIntensity\022:.building.illumin" +
      "ation_control.ModifyLightIntensityReques" +
      "t\032;.building.illumination_control.Modify" +
      "LightIntensityResponse\"\000\022v\n\013lightStatus\022" +
      "1.building.illumination_control.LightSta" +
      "tusRequest\0322.building.illumination_contr" +
      "ol.LightStatusResponse\"\000\022\210\001\n\021changeLight" +
      "Status\0227.building.illumination_control.C" +
      "hangeLightStatusRequest\0328.building.illum" +
      "ination_control.ChangeLightStatusRespons" +
      "e\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_building_illumination_control_ModifyLightIntensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_illumination_control_ModifyLightIntensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_ModifyLightIntensityRequest_descriptor,
        new java.lang.String[] { "AreaId", "Intensity", });
    internal_static_building_illumination_control_ModifyLightIntensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_building_illumination_control_ModifyLightIntensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_ModifyLightIntensityResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", });
    internal_static_building_illumination_control_LightStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_building_illumination_control_LightStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_LightStatusRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_building_illumination_control_LightStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_building_illumination_control_LightStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_LightStatusResponse_descriptor,
        new java.lang.String[] { "Status", "CurrentIntensity", });
    internal_static_building_illumination_control_ChangeLightStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_building_illumination_control_ChangeLightStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_ChangeLightStatusRequest_descriptor,
        new java.lang.String[] { "AreaId", "Status", });
    internal_static_building_illumination_control_ChangeLightStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_building_illumination_control_ChangeLightStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_illumination_control_ChangeLightStatusResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
