// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IlluminationManagementService.proto

package building.illumination_control;

public interface LightStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.illumination_control.LightStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();
}
