// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IlluminationManagementService.proto

package building.illumination_control;

public interface LightStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.illumination_control.LightStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>int32 current_intensity = 2;</code>
   */
  int getCurrentIntensity();
}
