// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IlluminationManagementService.proto

package building.illumination_control;

public interface ModifyLightIntensityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:building.illumination_control.ModifyLightIntensityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
